services:
  web:
    build: .
    command: sh start.sh
    volumes:
      - ./Disease-Prediction/:/app/
    ports:
      - "8000:8000"
    env_file:
      - ./Disease-Prediction/.env
    environment:
      - DEBUG=1
